import collections

sys_dic = collections.OrderedDict()
#"sys name"=["sys label","need run data",have hist, not use now],
sys_dic["nominal"]=["nominal",True,True,0]
sys_dic["muptscalu"]=["MuPtscal_up",True,True,0]
sys_dic["muptresu"]=["MuPtres_up",True,True,0]
sys_dic["eletscalu"]=["ElEtscal_up",True,True,0]
sys_dic["eletscald"]=["ElEtscal_down",True,True,0]
sys_dic["top1_u"]=["top_up",True,True,0]
sys_dic["top1_d"]=["top_down",True,True,0]
sys_dic["pu_u"]=["pileup_up",True,True,0]
sys_dic["pu_d"]=["pileup_down",True,True,0]

sys_dic["mu_id_sfu"]=["MuIDSF_up",True,True,0]
sys_dic["mu_iso_sfu"]=["MuISOSF_up",True,True,0]
sys_dic["mu_trig_sfu"]=["MuTrig_up",True,True,0]
sys_dic["el_id_sfu"]=["ElIDSF_up",True,True,0]
sys_dic["mu_id_sfd"]=["MuIDSF_down",True,True,0]
sys_dic["mu_iso_sfd"]=["MuISOSF_down",True,True,0]
sys_dic["mu_trig_sfd"]=["MuTrig_down",True,True,0]
sys_dic["el_id_sfd"]=["ElIDSF_down",True,True,0]

sys_dic["qcd_u"]=["QCD_up",False,True,0]
sys_dic["qcd_d"]=["QCD_down",False,True,0]
sys_dic["xs_ttbar_u"]=["XsTTbar_up",False,True,0]
sys_dic["xs_ttbar_d"]=["XsTTbar_down",False,True,0]
sys_dic["xs_ww_u"]=["XsWW_up",False,True,0]
sys_dic["xs_ww_d"]=["XsWW_down",False,True,0]
sys_dic["xs_st_u"]=["XsST_up",False,True,0]
sys_dic["xs_st_d"]=["XsST_down",False,True,0]
sys_dic["xs_dy_u"]=["XsDY_up",False,True,0]
sys_dic["xs_dy_d"]=["XsDY_down",False,True,0]
sys_dic["xs_wz_u"]=["XsWZ_up",False,True,0]
sys_dic["xs_wz_d"]=["XsWZ_down",False,True,0]
sys_dic["xs_zz_u"]=["XsZZ_up",False,True,0]
sys_dic["xs_zz_d"]=["XsZZ_down",False,True,0]
sys_dic["lumi_u"]=[":Lumi_up",False,True,0]
sys_dic["lumi_d"]=[":Lumi_down",False,True,0]