python extract_plot.py -r _EMu_ll
python extract_plot.py -r _EMu_llB1
python extract_plot.py -r _EMu_llBg1
python extract_plot.py -r _EMu_llMetg30
python extract_plot.py -r _EMu_llMetg30Jetg2B1
python extract_plot.py -r _EMu_llMetg30Jetg2Bg1
python extract_plot.py -r _EMu_llMetl30
python extract_plot.py -r _EMu_llMetl30Jetg2B1
python extract_plot.py -r _EMu_llMetl30Jetg2Bg1
#python extract_plot.py -r _EMu_llOffZ
