from input_setting import *

if GLOBAL_YEAR == "2016":
	from input_card_2016 import *
if GLOBAL_YEAR == "2017":
	from input_card_2017 import *
if GLOBAL_YEAR == "2018":
	from input_card_2018 import *

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

pre_plot_dic["compare_1"]["data"] = {
					"data_list":["data"],
					"color":1,
					"legend_title":"Data (%s)"%(GLOBAL_YEAR),
					"N_total":0.0,
					"hist":{},
					"ABS":False,
					}

pre_plot_dic["compare_2"]["_ttbar"] = {
					"data_list":["TTGJets","TTTo2L2Nu","TTWJetsToLNu","TTWJetsToQQ","TTZToLLNuNu_10","TTZToQQ"],
					"color":ROOT.kRed-4,
					"legend_title":"t#bar{t}",
					"N_total":0.0,
					"hist":{},
					"ABS":False,
					}
pre_plot_dic["compare_2"]["_tW"] = {
					"data_list":["tW","tW_anti"],
					"color":ROOT.kOrange-3,
					"legend_title":"tW",
					"N_total":0.0,
					"hist":{},
					"ABS":False,
					}
pre_plot_dic["compare_2"]["_ZG_jets"] = {
					"data_list":["DYToLL_10to50","DYToLL_50"],
					"color":ROOT.kBlue-3,
					"legend_title":"Z/#gamma^{*}+jets",
					"N_total":0.0,
					"hist":{},
					"ABS":False,
					}
pre_plot_dic["compare_2"]["_others"] = {
					"data_list":["WGToLNuG","WWTo2L2Nu","WZTo2L2Q","WZTo3LNu","ZZTo2L2Nu","ZZTo4L"],
					"color":ROOT.kGreen,
					"legend_title":"Diboson",
					"N_total":0.0,
					"hist":{},
					"ABS":False,
					}
#----fke jet----
if QCD_JET_BKG_TYPE == "same sign":
	pre_plot_dic["compare_2"]["qcd_jet"] = {
					"data_list":["ss_data","ss_TTGJets","ss_TTTo2L2Nu","ss_TTWJetsToLNu","ss_TTWJetsToQQ","ss_TTZToLLNuNu_10","ss_TTZToQQ","ss_tW","ss_tW_anti","ss_DYToLL_10to50","ss_DYToLL_50","ss_WGToLNuG","ss_WWTo2L2Nu","ss_WZTo2L2Q","ss_WZTo3LNu","ss_ZZTo2L2Nu","ss_ZZTo4L"],
					"color":ROOT.kYellow,
					"legend_title":"Jets",
					"N_total":0.0,
					"hist":{},
					"ABS":True,
					"weight_factor":1,
					}

if QCD_JET_BKG_TYPE == "MC":
	pre_plot_dic["compare_2"]["qcd_jet"] = {
					"data_list":["WGToLNuG"],
					"color":ROOT.kYellow,
					"legend_title":"Jets",
					"N_total":0.0,
					"hist":{},
					"ABS":True,
					}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

pre_plot_dic_ss["compare_1"]["data"] = {
					"data_list":["ss_data"],
					"color":1,
					"legend_title":"Data (%s)"%(GLOBAL_YEAR),
					"N_total":0.0,
					"hist":{},
					"ABS":False,
					}		
pre_plot_dic_ss["compare_2"]["_ttbar"] = {
					"data_list":["ss_TTGJets","ss_TTTo2L2Nu","ss_TTWJetsToLNu","ss_TTWJetsToQQ","ss_TTZToLLNuNu_10","ss_TTZToQQ"],
					"color":ROOT.kRed-4,
					"legend_title":"t#bar{t}",
					"N_total":0.0,
					"hist":{},
					"ABS":False,
					}
pre_plot_dic_ss["compare_2"]["_tW"] = {
					"data_list":["ss_tW","ss_tW_anti"],
					"color":ROOT.kOrange-3,
					"legend_title":"DY",
					"N_total":0.0,
					"hist":{},
					"ABS":False,
					}
pre_plot_dic_ss["compare_2"]["_ZG_jets"] = {
					"data_list":["ss_DYToLL_10to50","ss_DYToLL_50"],
					"color":ROOT.kBlue-3,
					"legend_title":"Z/#gamma^{*}+jets",
					"N_total":0.0,
					"hist":{},
					"ABS":False,
					}
pre_plot_dic_ss["compare_2"]["_others"] = {
					"data_list":["ss_WGToLNuG","ss_WWTo2L2Nu","ss_WZTo2L2Q","ss_WZTo3LNu","ss_ZZTo2L2Nu","ss_ZZTo4L"],
					"color":ROOT.kGreen,
					"legend_title":"Other",
					"N_total":0.0,
					"hist":{},
					"ABS":False,
					}

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

pre_input_dic["DYToLL_10to50"] = {
		"isFromRoot":True,
		"input_file":"80_DYToLL_10to50.root",
		"isData":False,
		"isFake":False,
		"isSS":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_DYToLL_10to50,
		"N_total": 0.0,
		"Raw_total":nevent_DYToLL_10to50,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":50,
		"weight_factor":1,
		"hist":{},
		"isUpdate":isUpdate
		}
pre_input_dic["DYToLL_50"] = {
		"isFromRoot":True,
		"input_file":"80_DYToLL_50.root",
		"isData":False,
		"isFake":False,
		"isSS":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_DYToLL_50,
		"N_total": 0.0,
		"Raw_total":nevent_DYToLL_50,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":5,
		"weight_factor":1,
		"hist":{},
		"isUpdate":isUpdate
		}
pre_input_dic["TTGJets"] = {
		"isFromRoot":True,
		"input_file":"80_TTGJets.root",
		"isData":False,
		"isFake":False,
		"isSS":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_TTGJets,
		"N_total": 0.0,
		"Raw_total":nevent_TTGJets,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":1,
		"hist":{},
		"isUpdate":isUpdate
		}
pre_input_dic["TTTo2L2Nu"] = {
		"isFromRoot":True,
		"input_file":"80_TTTo2L2Nu.root",
		"isData":False,
		"isFake":False,
		"isSS":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_TTTo2L2Nu,
		"N_total": 0.0,
		"Raw_total":nevent_TTTo2L2Nu,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":1,
		"hist":{},
		"isUpdate":isUpdate
		}
pre_input_dic["TTWJetsToLNu"] = {
		"isFromRoot":True,
		"input_file":"80_TTWJetsToLNu.root",
		"isData":False,
		"isFake":False,
		"isSS":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_TTWJetsToLNu,
		"N_total": 0.0,
		"Raw_total":nevent_TTWJetsToLNu,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":1,
		"hist":{},
		"isUpdate":isUpdate
		}
pre_input_dic["TTWJetsToQQ"] = {
		"isFromRoot":True,
		"input_file":"80_TTWJetsToQQ.root",
		"isData":False,
		"isFake":False,
		"isSS":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_TTWJetsToQQ,
		"N_total": 0.0,
		"Raw_total":nevent_TTWJetsToQQ,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":1,
		"hist":{},
		"isUpdate":isUpdate
		}
pre_input_dic["TTZToLLNuNu_10"] = {
		"isFromRoot":True,
		"input_file":"80_TTZToLLNuNu_10.root",
		"isData":False,
		"isFake":False,
		"isSS":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_TTZToLLNuNu_10,
		"N_total": 0.0,
		"Raw_total":nevent_TTZToLLNuNu_10,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":1,
		"hist":{},
		"isUpdate":isUpdate
		}
pre_input_dic["TTZToQQ"] = {
		"isFromRoot":True,
		"input_file":"80_TTZToQQ.root",
		"isData":False,
		"isFake":False,
		"isSS":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_TTZToQQ,
		"N_total": 0.0,
		"Raw_total":nevent_TTZToQQ,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":1,
		"hist":{},
		"isUpdate":isUpdate
		}
pre_input_dic["WGToLNuG"] = {
		"isFromRoot":True,
		"input_file":"80_WGToLNuG.root",
		"isData":False,
		"isFake":False,
		"isSS":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_WGToLNuG,
		"N_total": 0.0,
		"Raw_total":nevent_WGToLNuG,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":1,
		"hist":{},
		"isUpdate":isUpdate
		}
pre_input_dic["WJetsToLNu"] = {
		"isFromRoot":True,
		"input_file":"80_WJetsToLNu.root",
		"isData":False,
		"isFake":False,
		"isSS":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_WJetsToLNu,
		"N_total": 0.0,
		"Raw_total":nevent_WJetsToLNu,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":1,
		"hist":{},
		"isUpdate":isUpdate
		}
pre_input_dic["WWTo2L2Nu"] = {
		"isFromRoot":True,
		"input_file":"80_WWTo2L2Nu.root",
		"isData":False,
		"isFake":False,
		"isSS":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_WWTo2L2Nu,
		"N_total": 0.0,
		"Raw_total":nevent_WWTo2L2Nu,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":1,
		"hist":{},
		}
pre_input_dic["WZTo2L2Q"] = {
		"isFromRoot":True,
		"input_file":"80_WZTo2L2Q.root",
		"isData":False,
		"isFake":False,
		"isSS":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_WZTo2L2Q,
		"N_total": 0.0,
		"Raw_total":nevent_WZTo2L2Q,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":1,
		"hist":{},
		"isUpdate":isUpdate
		}
pre_input_dic["WZTo3LNu"] = {
		"isFromRoot":True,
		"input_file":"80_WZTo3LNu.root",
		"isData":False,
		"isFake":False,
		"isSS":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_WZTo3LNu,
		"N_total": 0.0,
		"Raw_total":nevent_WZTo3LNu,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":1,
		"hist":{},
		"isUpdate":isUpdate
		}
pre_input_dic["ZZTo2L2Nu"] = {
		"isFromRoot":True,
		"input_file":"80_ZZTo2L2Nu.root",
		"isData":False,
		"isFake":False,
		"isSS":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_ZZTo2L2Nu,
		"N_total": 0.0,
		"Raw_total":nevent_ZZTo2L2Nu,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":1,
		"hist":{},
		"isUpdate":isUpdate
		}
pre_input_dic["ZZTo4L"] = {
		"isFromRoot":True,
		"input_file":"80_ZZTo4L.root",
		"isData":False,
		"isFake":False,
		"isSS":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_ZZTo4L,
		"N_total": 0.0,
		"Raw_total":nevent_ZZTo4L,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":1,
		"hist":{},
		"isUpdate":isUpdate
		}
pre_input_dic["tW"] = {
		"isFromRoot":True,
		"input_file":"80_tW.root",
		"isData":False,
		"isFake":False,
		"isSS":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_tw,
		"N_total": 0.0,
		"Raw_total":nevent_tw,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":1,
		"hist":{},
		"isUpdate":isUpdate
		}
pre_input_dic["tW_anti"] = {
		"isFromRoot":True,
		"input_file":"80_tW_anti.root",
		"isData":False,
		"isFake":False,
		"isSS":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_tw_anti,
		"N_total": 0.0,
		"Raw_total":nevent_tw_anti,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":1,
		"hist":{},
		"isUpdate":isUpdate
		}

if QCD_JET_BKG_TYPE == "same sign":

	pre_input_dic["ss_DYToLL_10to50"] = {
		"isFromRoot":True,
		"input_file":"80_DYToLL_10to50.root",
		"isData":False,
		"isSS":True,
		"isFake":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_DYToLL_10to50,
		"N_total": 0.0,
		"Raw_total":nevent_DYToLL_10to50,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":50,
		"weight_factor":-1,
		"hist":{},
		"isUpdate":isUpdate
		}
	pre_input_dic["ss_DYToLL_50"] = {
		"isFromRoot":True,
		"input_file":"80_DYToLL_50.root",
		"isData":False,
		"isSS":True,
		"isFake":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_DYToLL_50,
		"N_total": 0.0,
		"Raw_total":nevent_DYToLL_50,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":5,
		"weight_factor":-1,
		"hist":{},
		"isUpdate":isUpdate
		}
	pre_input_dic["ss_TTGJets"] = {
		"isFromRoot":True,
		"input_file":"80_TTGJets.root",
		"isData":False,
		"isSS":True,
		"isFake":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_TTGJets,
		"N_total": 0.0,
		"Raw_total":nevent_TTGJets,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":-1,
		"hist":{},
		"isUpdate":isUpdate
		}
	pre_input_dic["ss_TTTo2L2Nu"] = {
		"isFromRoot":True,
		"input_file":"80_TTTo2L2Nu.root",
		"isData":False,
		"isSS":True,
		"isFake":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_TTTo2L2Nu,
		"N_total": 0.0,
		"Raw_total":nevent_TTTo2L2Nu,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":-1,
		"hist":{},
		"isUpdate":isUpdate
		}
	pre_input_dic["ss_TTWJetsToLNu"] = {
		"isFromRoot":True,
		"input_file":"80_TTWJetsToLNu.root",
		"isData":False,
		"isSS":True,
		"isFake":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_TTWJetsToLNu,
		"N_total": 0.0,
		"Raw_total":nevent_TTWJetsToLNu,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":-1,
		"hist":{},
		"isUpdate":isUpdate
		}
	pre_input_dic["ss_TTWJetsToQQ"] = {
		"isFromRoot":True,
		"input_file":"80_TTWJetsToQQ.root",
		"isData":False,
		"isSS":True,
		"isFake":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_TTWJetsToQQ,
		"N_total": 0.0,
		"Raw_total":nevent_TTWJetsToQQ,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":-1,
		"hist":{},
		"isUpdate":isUpdate
		}
	pre_input_dic["ss_TTZToLLNuNu_10"] = {
		"isFromRoot":True,
		"input_file":"80_TTZToLLNuNu_10.root",
		"isData":False,
		"isSS":True,
		"isFake":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_TTZToLLNuNu_10,
		"N_total": 0.0,
		"Raw_total":nevent_TTZToLLNuNu_10,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":-1,
		"hist":{},
		"isUpdate":isUpdate
		}
	pre_input_dic["ss_TTZToQQ"] = {
		"isFromRoot":True,
		"input_file":"80_TTZToQQ.root",
		"isData":False,
		"isSS":True,
		"isFake":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_TTZToQQ,
		"N_total": 0.0,
		"Raw_total":nevent_TTZToQQ,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":-1,
		"hist":{},
		"isUpdate":isUpdate
		}
	pre_input_dic["ss_WGToLNuG"] = {
		"isFromRoot":True,
		"input_file":"80_WGToLNuG.root",
		"isData":False,
		"isSS":True,
		"isFake":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_WGToLNuG,
		"N_total": 0.0,
		"Raw_total":nevent_WGToLNuG,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":-1,
		"hist":{},
		"isUpdate":isUpdate
		}
	pre_input_dic["ss_WJetsToLNu"] = {
		"isFromRoot":True,
		"input_file":"80_WJetsToLNu.root",
		"isData":False,
		"isSS":True,
		"isFake":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_WJetsToLNu,
		"N_total": 0.0,
		"Raw_total":nevent_WJetsToLNu,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":-1,
		"hist":{},
		"isUpdate":isUpdate
		}
	pre_input_dic["ss_WWTo2L2Nu"] = {
		"isFromRoot":True,
		"input_file":"80_WWTo2L2Nu.root",
		"isData":False,
		"isSS":True,
		"isFake":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_WWTo2L2Nu,
		"N_total": 0.0,
		"Raw_total":nevent_WWTo2L2Nu,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":-1,
		"hist":{},
		"isUpdate":isUpdate
		}
	pre_input_dic["ss_WZTo2L2Q"] = {
		"isFromRoot":True,
		"input_file":"80_WZTo2L2Q.root",
		"isData":False,
		"isSS":True,
		"isFake":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_WZTo2L2Q,
		"N_total": 0.0,
		"Raw_total":nevent_WZTo2L2Q,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":-1,
		"hist":{},
		"isUpdate":isUpdate
		}
	pre_input_dic["ss_WZTo3LNu"] = {
		"isFromRoot":True,
		"input_file":"80_WZTo3LNu.root",
		"isData":False,
		"isSS":True,
		"isFake":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_WZTo3LNu,
		"N_total": 0.0,
		"Raw_total":nevent_WZTo3LNu,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":-1,
		"hist":{},
		"isUpdate":isUpdate
		}
	pre_input_dic["ss_ZZTo2L2Nu"] = {
		"isFromRoot":True,
		"input_file":"80_ZZTo2L2Nu.root",
		"isData":False,
		"isSS":True,
		"isFake":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_ZZTo2L2Nu,
		"N_total": 0.0,
		"Raw_total":nevent_ZZTo2L2Nu,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":-1,
		"hist":{},
		"isUpdate":isUpdate
		}
	pre_input_dic["ss_ZZTo4L"] = {
		"isFromRoot":True,
		"input_file":"80_ZZTo4L.root",
		"isData":False,
		"isSS":True,
		"isFake":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_ZZTo4L,
		"N_total": 0.0,
		"Raw_total":nevent_ZZTo4L,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":-1,
		"hist":{},
		"isUpdate":isUpdate
		}
	pre_input_dic["ss_tW"] = {
		"isFromRoot":True,
		"input_file":"80_tW.root",
		"isData":False,
		"isSS":True,
		"isFake":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_tw,
		"N_total": 0.0,
		"Raw_total":nevent_tw,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":-1,
		"hist":{},
		"isUpdate":isUpdate
		}
	pre_input_dic["ss_tW_anti"] = {
		"isFromRoot":True,
		"input_file":"80_tW_anti.root",
		"isData":False,
		"isSS":True,
		"isFake":False,
		"useToNorm":False,
		"lumi":0.0,
		"Xsection":xsection_tw_anti,
		"N_total": 0.0,
		"Raw_total":nevent_tw_anti,
		"N_norm":1.0,
		"Norm_Factor":1,
		"Fill_color":30,
		"weight_factor":-1,
		"hist":{},
		"isUpdate":isUpdate
		}

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

n_jet_bjet_dic = {
"(0,0)":[0,1,"(0,0)"],
"(1,0)":[1,2,"(1,0)"],
"(1,1)":[2,3,"(1,1)"],
"(2,0)":[3,4,"(2,0)"],
"(2,1)":[4,5,"(2,1)"],
"(2,2)":[5,6,"(2,2)"],
"(3,0)":[6,7,"(3,0)"],
"(3,1)":[7,8,"(3,1)"],
"(3,2)":[8,9,"(3,2)"],
"(3,3)":[9,10,"(3,3)"],
"(4,0)":[10,11,"(4,0)"],
"(4,1)":[11,12,"(4,1)"],
"(4,2)":[12,13,"(4,2)"],
"(4,3)":[13,14,"(4,3)"],
"(4,4)":[14,15,"(4,4)"],
"(>4,n)":[15,16,"(>4,n)"],
}
n_jet_bjet_dic2 = {
"(1,0)":[0,1,"(1,0)"],
"(1,1)":[1,2,"(1,1)"],
"(2,1)":[2,3,"(2,1)"],
"(>=3,1)":[3,4,"(>=3,1)"],
"(>=3,>1)":[4,5,"(>=3,>1)"],
}

pre_value_dic["new_M_ll"] = {
	"Data_value_dic":{"M_ll":True},
	"MC_value_dic":{"M_ll":True},
	"hist_name":"new_M_ll",
	"hist_title":"Invirant mass(Di-lepton)",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[20,None,0,200],
	"y_axis":["null","null"],
	"x_label":['M_{ll} (GeV/c^{2})',0.1],
	"y_label":['Event / 10 GeV',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["M_ll_zmass"] = {
	"Data_value_dic":{"M_ll":True},
	"MC_value_dic":{"M_ll":True},
	"hist_name":"M_ll_zmass",
	"hist_title":"Invirant mass(Di-lepton)",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[12,None,60,120],
	"y_axis":["null","null"],
	"x_label":['M_{ll} (GeV/c^{2})',0.1],
	"y_label":['Event / 5 GeV',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["Pt_ll"] = {
	"Data_value_dic":{"M_ll":True},
	"MC_value_dic":{"M_ll":True},
	"hist_name":"Pt_ll",
	"hist_title":"Pt (Di-lepton)",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,0,200],
	"y_axis":["null","null"],
	"x_label":['P_{T}^{ll} (GeV/c^{2})',0.1],
	"y_label":['Event / 20 GeV',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["phi_ll"] = {
	"Data_value_dic":{"":True},
	"MC_value_dic":{"":True},
	"hist_name":"phi_ll",
	"hist_title":"Pt (Di-lepton)",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,-3.5,3.5],
	"y_axis":["null","null"],
	"x_label":['#phi^{ll} ',0.1],
	"y_label":['Event / 0.7',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["deltaR_ll"] = {
	"Data_value_dic":{"":True},
	"MC_value_dic":{"":True},
	"hist_name":"deltaR_ll",
	"hist_title":"Pt (Di-lepton)",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[15,None,0,6],
	"y_axis":["null","null"],
	"x_label":['#Delta R(l,l)',0.1],
	"y_label":['Event / 0.4',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["rapidity_ll"] = {
	"Data_value_dic":{"":True},
	"MC_value_dic":{"":True},
	"hist_name":"rapidity_ll",
	"hist_title":"Pt (Di-lepton)",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,-3,3],
	"y_axis":["null","null"],
	"x_label":['Rapidity^{ll}',0.1],
	"y_label":['Event / 1',0.6],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["new_leading_pt"] = {
	"Data_value_dic":{"leading_pt":True},
	"MC_value_dic":{"leading_pt":True},
	"hist_name":"new_leading_pt",
	"hist_title":"Leading Lepton Pt",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,0,200],
	"y_axis":["null","null"],
	"x_label":['P_{T}^{leading lep} (GeV/c)',0.1],
	"y_label":['Event / 20 GeV',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["new_leading_pt_muon"] = {
	"Data_value_dic":{"leading_pt":"getattr(event,'leading_isMu')"},
	"MC_value_dic":{"leading_pt":"getattr(event,'leading_isMu')"},
	"hist_name":"new_leading_pt_muon",
	"hist_title":"Leading Lepton Pt",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,0,200],
	"y_axis":["null","null"],
	"x_label":['P_{T}^{leading muon} (GeV/c)',0.1],
	"y_label":['Event / 20 GeV',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["new_leading_pt_ele"] = {
	"Data_value_dic":{"leading_pt":"getattr(event,'leading_isE')"},
	"MC_value_dic":{"leading_pt":"getattr(event,'leading_isE')"},
	"hist_name":"new_leading_pt_ele",
	"hist_title":"Leading Lepton Pt",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,0,200],
	"y_axis":["null","null"],
	"x_label":['P_{T}^{leading ele} (GeV/c)',0.1],
	"y_label":['Event / 20 GeV',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["leading_eta_muon"] = {
	"Data_value_dic":{"leading_eta":"getattr(event,'leading_isMu')"},
	"MC_value_dic":{"leading_eta":"getattr(event,'leading_isMu')"},
	"hist_name":"muon_leading_eta",
	"hist_title":"Leading muon #eta",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,-2.5,2.5],
	"y_axis":["null","null"],
	"x_label":['#eta^{leading muon}',0.1],
	"y_label":['Event / 0.5',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["leading_eta_ele"] = {
	"Data_value_dic":{"leading_eta":"getattr(event,'leading_isE')"},
	"MC_value_dic":{"leading_eta":"getattr(event,'leading_isE')"},
	"hist_name":"electron_leading_eta",
	"hist_title":"Leading electron #eta",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,-2.5,2.5],
	"y_axis":["null","null"],
	"x_label":['#eta^{leading electron}',0.1],
	"y_label":['Event / 0.5',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["leading_eta"] = {
	"Data_value_dic":{"leading_eta":True},
	"MC_value_dic":{"leading_eta":True},
	"hist_name":"leading_eta",
	"hist_title":"Leading Lepton #eta",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,-2.5,2.5],
	"y_axis":["null","null"],
	"x_label":['#eta^{leading lepton}',0.1],
	"y_label":['Event / 0.5',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["leading_phi"] = {
	"Data_value_dic":{"leading_phi":True},
	"MC_value_dic":{"leading_phi":True},
	 "hist_name":"leading_phi",
	"hist_title":"Leading Lepton #phi",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,-3.5,3.5],
	"y_axis":["null","null"],
	"x_label":['#phi^{leading lepton}',0.1],
	"y_label":['Event / 0.7',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["new_sub_leading_pt"] = {
	"Data_value_dic":{"sub_leading_pt":True},
	"MC_value_dic":{"sub_leading_pt":True},
	"hist_name":"new_sub_leading_pt",
	"hist_title":"Sub-Leading Lepton Pt",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,0,200],
	"y_axis":["null","null"],
	"x_label":['P_{T}^{subleading lepton} (GeV/c)',0.1],
	"y_label":['Event / 20 GeV',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["new_sub_leading_pt_muon"] = {
	"Data_value_dic":{"sub_leading_pt":"getattr(event,'sub_leading_isMu')"},
	"MC_value_dic":{"sub_leading_pt":"getattr(event,'sub_leading_isMu')"},
	"hist_name":"new_sub_leading_pt_muon",
	"hist_title":"sub_leading Lepton Pt",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,0,200],
	"y_axis":["null","null"],
	"x_label":['P_{T}^{sub_leading muon} (GeV/c)',0.1],
	"y_label":['Event / 20 GeV',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["new_sub_leading_pt_ele"] = {
	"Data_value_dic":{"sub_leading_pt":"getattr(event,'sub_leading_isE')"},
	"MC_value_dic":{"sub_leading_pt":"getattr(event,'sub_leading_isE')"},
	"hist_name":"new_sub_leading_pt_ele",
	"hist_title":"sub_leading Lepton Pt",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,0,200],
	"y_axis":["null","null"],
	"x_label":['P_{T}^{sub_leading ele} (GeV/c)',0.1],
	"y_label":['Event / 20 GeV',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["sub_leading_eta"] = {
	"Data_value_dic":{"sub_leading_eta":True},
	"MC_value_dic":{"sub_leading_eta":True},
	"hist_name":"sub_leading_eta",
	"hist_title":"sub_Leading Lepton #eta",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,-2.5,2.5],
	"y_axis":["null","null"],
	"x_label":['#eta^{subleading lepton}',0.1],
	"y_label":['Event / 0.5',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["sub_leading_eta_muon"] = {
	"Data_value_dic":{"sub_leading_eta":"getattr(event,'sub_leading_isMu')"},
	"MC_value_dic":{"sub_leading_eta":"getattr(event,'sub_leading_isMu')"},
	"hist_name":"muon_sub_leading_eta",
	"hist_title":"sub_Leading muon #eta",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,-2.5,2.5],
	"y_axis":["null","null"],
	"x_label":['#eta^{subleading muon}',0.1],
	"y_label":['Event / 0.5',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["sub_leading_eta_ele"] = {
	"Data_value_dic":{"sub_leading_eta":"getattr(event,'sub_leading_isE')"},
	"MC_value_dic":{"sub_leading_eta":"getattr(event,'sub_leading_isE')"},
	"hist_name":"electron_sub_leading_eta",
	"hist_title":"sub_Leading electron #eta",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,-2.5,2.5],
	"y_axis":["null","null"],
	"x_label":['#eta^{subleading electron}',0.1],
	"y_label":['Event / 0.5',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["sub_leading_phi"] = {
	"Data_value_dic":{"sub_leading_phi":True},
	"MC_value_dic":{"sub_leading_phi":True},
	"hist_name":"sub_leading_phi",
	"hist_title":"sub-Leading Lepton #phi",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,-3.5,3.5],
	"y_axis":["null","null"],
	"x_label":['#phi^{subleading lepton}',0.1],
	"y_label":['Event / 0.7',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["MET_pt"] = {
	"Data_value_dic":{"MET_FinalCollection_Pt":True},
	"MC_value_dic":{"MET_FinalCollection_Pt":True},
	"hist_name":"MET_Pt",
	"hist_title":"MET Pt",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[20,None,0,120],
	"y_axis":["null","null"],
	"x_label":['MET (GeV/c)',0.1],
	"y_label":['Event / 6 GeV',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["MET_phi"] = {
	"Data_value_dic":{"MET_FinalCollection_phi":True},
	"MC_value_dic":{"MET_FinalCollection_phi":True},
	"hist_name":"MET_phi",
	"hist_title":"MET #phi",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,-3.5,3.5],
	"y_axis":["null","null"],
	"x_label":['MET_{#phi}',0.1],
	"y_label":['Event / 0.7',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["MET_significance"] = {
	"Data_value_dic":{"MET_FinalCollection_significance":True},
	"MC_value_dic":{"MET_FinalCollection_significance":True},
	"hist_name":"MET_significance",
	"hist_title":"MET significance",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,0,20],
	"y_axis":["null","null"],
	"x_label":['MET_{significance}',0.1],
	"y_label":['Event / 2',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["MET_pt_corr"] = {
	"Data_value_dic":{"MET_OfflineCorrect_Pt":True},
	"MC_value_dic":{"MET_OfflineCorrect_Pt":True},
	"hist_name":"MET_pt_corr",
	"hist_title":"MET Pt",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[20,None,0,120],
	"y_axis":["null","null"],
	"x_label":['MET Offline Corr (GeV/c)',0.1],
	"y_label":['Event / 6 GeV',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["MET_phi_corr"] = {
	"Data_value_dic":{"MET_OfflineCorrect_phi":True},
	"MC_value_dic":{"MET_OfflineCorrect_phi":True},
	"hist_name":"MET_phi_corr",
	"hist_title":"MET #phi",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,-3.5,3.5],
	"y_axis":["null","null"],
	"x_label":['MET_{#phi} Offline Corr',0.1],
	"y_label":['Event / 0.7',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["MET_T1Txy_pt"] = {
	"Data_value_dic":{"MET_T1Txy_Pt":True},
	"MC_value_dic":{"MET_T1Txy_Pt":True},
	"hist_name":"MET_T1Txy_Pt",
	"hist_title":"MET T1Txy Pt",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[20,None,0,120],
	"y_axis":["null","null"],
	"x_label":['MET^{T1Txy} (GeV/c)',0.1],
	"y_label":['Event / 6 GeV',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["MET_T1Txy_phi"] = {
	"Data_value_dic":{"MET_T1Txy_phi":True},
	"MC_value_dic":{"MET_T1Txy_phi":True},
	"hist_name":"MET_T1Txy_phi",
	"hist_title":"MET T1Txy #phi",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,-3.5,3.5],
	"y_axis":["null","null"],
	"x_label":['MET^{T1Txy}_{#phi}',0.1],
	"y_label":['Event / 0.7',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["Z_MET_T1Txy_delta_phi"] = {
	"Data_value_dic":{"MET_T1Txy_phi":True},
	"MC_value_dic":{"MET_T1Txy_phi":True},
	"hist_name":"Z_MET_T1Txy_delta_phi",
	"hist_title":"MET T1Txy #phi",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,0,3.5],
	"y_axis":["null","null"],
	"x_label":['#delta #phi(MET^{T1Txy},ll)',0.1],
	"y_label":['Event / 0.35',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["MET_T1Txy_significance"] = {
	"Data_value_dic":{"MET_T1Txy_significance":True},
	"MC_value_dic":{"MET_T1Txy_significance":True},
	"hist_name":"MET_T1Txy_significance",
	"hist_title":"MET T1Txy significance",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,0,20],
	"y_axis":["null","null"],
	"x_label":['MET^{T1Txy}_{significance}',0.1],
	"y_label":['Event / 2',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["rho"] = {
	"Data_value_dic":{"ev_fixedGridRhoAll":True},
	"MC_value_dic":{"ev_fixedGridRhoAll":True},
	"hist_name":"rho_all",
	"hist_title":"ev_fixedGridRhoAll",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,0,50],
	"y_axis":["null","null"],
	"x_label":['#rho',0.1],
	"y_label":['Event / 5',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["n_jet"] = {
	"Data_value_dic":{"n_jet":True},
	"MC_value_dic":{"n_jet":True},
	"hist_name":"n_jet",
	"hist_title":"Jet Multiplicity",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,0,10],
	"y_axis":["null","null"],
	"x_label":['N_{jet}',0.1],
	"y_label":['Event / 1',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["n_bjet"] = {
	"Data_value_dic":{"n_bjet":True},
	"MC_value_dic":{"n_bjet":True},
	"hist_name":"n_bjet",
	"hist_title":"Jet Multiplicity",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[6,None,0,6],
	"y_axis":["null","null"],
	"x_label":['N_{b jet}',0.1],
	"y_label":['Event / 1',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["n_bjet2"] = {
	"Data_value_dic":{"":True},
	"MC_value_dic":{"":True},
	"hist_name":"n_bjet2",
	"hist_title":"Jet Multiplicity",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[6,None,0,6],
	"y_axis":["null","null"],
	"x_label":['N_{b jet} (p_{T} in [20,30])',0.1],
	"y_label":['Event / 1',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["n_fjet1"] = {
	"Data_value_dic":{"":True},
	"MC_value_dic":{"":True},
	"hist_name":"n_fjet1",
	"hist_title":"Jet Multiplicity",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[6,None,0,6],
	"y_axis":["null","null"],
	"x_label":['N_{jet} (p_{T} > 30, |#eta| in [2.4,5.2])',0.1],
	"y_label":['Event / 1',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["n_fjet2"] = {
	"Data_value_dic":{"":True},
	"MC_value_dic":{"":True},
	"hist_name":"n_fjet2",
	"hist_title":"Jet Multiplicity",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[6,None,0,6],
	"y_axis":["null","null"],
	"x_label":['N_{jet} (p_{T} > 40, |#eta| in [2.4,5.2])',0.1],
	"y_label":['Event / 1',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["n_jet_bjet"] = {
	"Data_value_dic":{"":True},
	"MC_value_dic":{"":True},
	"hist_name":"n_jet_bjet",
	"hist_title":"Jet Multiplicity",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[len(n_jet_bjet_dic),None,0,len(n_jet_bjet_dic)],
	"y_axis":["null","null"],
	"x_label":['N_{(jet, b jet)}',0.1],
	"y_label":['Event / 1',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["n_jet_bjet2"] = {
	"Data_value_dic":{"":True},
	"MC_value_dic":{"":True},
	"hist_name":"n_jet_bjet2",
	"hist_title":"Jet Multiplicity",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[len(n_jet_bjet_dic2),None,0,len(n_jet_bjet_dic2)],
	"y_axis":["null","null"],
	"x_label":['N_{(jet, b jet)}',0.1],
	"y_label":['Event / 1',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["jet_leading_pt"] = {
	"Data_value_dic":{"":True},
	"MC_value_dic":{"":True},
	"hist_name":"jet_leading_pt",
	"hist_title":"Leading Jet Pt",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,0,200],
	"y_axis":["null","null"],
	"x_label":['P_{T}^{leading jet} (GeV/c)',0.1],
	"y_label":['Event / 20 GeV',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["jet_leading_eta"] = {
	"Data_value_dic":{"":True},
	"MC_value_dic":{"":True},
	"hist_name":"jet_leading_eta",
	"hist_title":"Leading Jet #eta",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,-2.5,2.5],
	"y_axis":["null","null"],
	"x_label":['#eta^{leading jet}',0.1],
	"y_label":['Event / 0.5',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["jet_leading_phi"] = {
	"Data_value_dic":{"":True},
	"MC_value_dic":{"":True},
	"hist_name":"jet_leading_phi",
	"hist_title":"Leading Jet #phi",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,-3.5,3.5],
	"y_axis":["null","null"],
	"x_label":['#phi^{leading jet}',0.1],
	"y_label":['Event / 0.7',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["jet_leading_CSV"] = {
	"Data_value_dic":{"":True},
	"MC_value_dic":{"":True},
	"hist_name":"jet_leading_CSV",
	"hist_title":"Leading Jet scv",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,0,1.0],
	"y_axis":["null","null"],
	"x_label":['CSV^{leading jet}',0.1],
	"y_label":['Event / 0.1',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["jet_sub_leading_pt"] = {
	"Data_value_dic":{"":True},
	"MC_value_dic":{"":True},
	"hist_name":"jet_sub_leading_pt",
	"hist_title":"Sub-Leading Jet Pt",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,0,200],
	"y_axis":["null","null"],
	"x_label":['P_{T}^{subleading jet} (GeV/c)',0.1],
	"y_label":['Event / 20 GeV',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["jet_sub_leading_eta"] = {
	"Data_value_dic":{"":True},
	"MC_value_dic":{"":True},
	"hist_name":"jet_sub_leading_eta",
	"hist_title":"sub_Leading Jet #eta",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,-2.5,2.5],
	"y_axis":["null","null"],
	"x_label":['#eta^{subleading jet}',0.1],
	"y_label":['Event / 0.5',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["jet_sub_leading_phi"] = {
	"Data_value_dic":{"":True},
	"MC_value_dic":{"":True},
	"hist_name":"jet_sub_leading_phi",
	"hist_title":"sub-Leading Jet #phi",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,-3.5,3.5],
	"y_axis":["null","null"],
	"x_label":['#phi^{subleading jet}',0.1],
	"y_label":['Event / 0.7',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["jet_sub_leading_CSV"] = {
	"Data_value_dic":{"":True},
	"MC_value_dic":{"":True},
	"hist_name":"jet_sub_leading_CSV",
	"hist_title":"sub-Leading Jet scv",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[10,None,0,1.0],
	"y_axis":["null","null"],
	"x_label":['CSV^{subleading jet}',0.1],
	"y_label":['Event / 0.1',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["HT"] = {
	"Data_value_dic":{"":True},
	"MC_value_dic":{"":True},
	"hist_name":"Ht",
	"hist_title":"Ht",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[20,None,0,2000],
	"y_axis":["null","null"],
	"x_label":['HT (GeV)',0.1],
	"y_label":['Event / 10 GeV',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["HT_log"] = {
	"Data_value_dic":{"":True},
	"MC_value_dic":{"":True},
	"hist_name":"Ht_log",
	"hist_title":"Ht",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[20,None,0,2000],
	"y_axis":["null","null"],
	"x_label":['HT (GeV)',0.1],
	"y_label":['Event / 10 GeV',0.05],
	"x_log":False,
	"y_log":True,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["sys_HT"] = {
	"Data_value_dic":{"":True},
	"MC_value_dic":{"":True},
	"hist_name":"sys_Ht",
	"hist_title":"sys Ht",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[20,None,0,2000],
	"y_axis":["null","null"],
	"x_label":['HT^{sys} (GeV)',0.1],
	"y_label":['Event / 10 GeV',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["sys_HT_log"] = {
	"Data_value_dic":{"":True},
	"MC_value_dic":{"":True},
	"hist_name":"sys_Ht_log",
	"hist_title":"sys Ht",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[20,None,0,2000],
	"y_axis":["null","null"],
	"x_label":['HT^{sys} (GeV)',0.1],
	"y_label":['Event / 10 GeV',0.05],
	"x_log":False,
	"y_log":True,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["pv_n"] = {
	"Data_value_dic":{"pv_n":True},
	"MC_value_dic":{"pv_n":True},
	"hist_name":"N_vtx_PU",
	"hist_title":"Number of vertex (with PU reweight)",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[100,None,0,100],
	"y_axis":["null","null"],
	"x_label":['N_{vtx}',0.1],
	"y_label":['Event ',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["pv_n_noPU"] = {
	"Data_value_dic":{"pv_n":True},
	"MC_value_dic":{"pv_n":True},
	"hist_name":"N_vtx_noPU",
	"hist_title":"Number of vertex (without PU reweight)",
	"use_array":False,
	"PU_reweight":False,
	"hist_para":[100,None,0,100],
	"y_axis":["null","null"],
	"x_label":['N_{vtx}^{no PU}',0.1],
	"y_label":['Event ',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}
pre_value_dic["n_stat"] = {
	"Data_value_dic":{"pv_n":True},
	"MC_value_dic":{"pv_n":True},
	"hist_name":"N_stat",
	"hist_title":"",
	"use_array":False,
	"PU_reweight":True,
	"hist_para":[1,None,0,1],
	"y_axis":["null","null"],
	"x_label":['N_stat',0.1],
	"y_label":['Event ',0.05],
	"x_log":False,
	"y_log":False,
	"lenend":{
		"useLegend":True,
		"position":[],
		},
	}

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
def getP4(pt, eta, phi, isE, isMu):
	p4 = ROOT.TLorentzVector()
	if isE:
		p4.SetPtEtaPhiM(pt,eta,phi,0.000511)
	else:
		p4.SetPtEtaPhiM(pt,eta,phi,0.10566)
	return p4

def getbinwidth(x,x1):
	for i in range(len(x1)):
		if x < x1[i] and i>0:
			return (x1[i]-x1[i-1])
		elif x < x1[i]:
			return -1.0
	return -1.0


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~