python merge_plot.py -r _EMu_ll
python merge_plot.py -r _EMu_llB1
python merge_plot.py -r _EMu_llBg1
python merge_plot.py -r _EMu_llMetg30
python merge_plot.py -r _EMu_llMetg30Jetg2B1
python merge_plot.py -r _EMu_llMetg30Jetg2Bg1
python merge_plot.py -r _EMu_llMetl30
python merge_plot.py -r _EMu_llMetl30Jetg2B1
python merge_plot.py -r _EMu_llMetl30Jetg2Bg1
#python merge_plot.py -r _EMu_llOffZ