python merge_plot.py -r _ALL
python merge_plot.py -r _ALL_2b
python merge_plot.py -r _BB
python merge_plot.py -r _BE
python merge_plot.py -r _EB
python merge_plot.py -r _EE
python merge_plot.py -r _MET_0to25
python merge_plot.py -r _MET_25to50
python merge_plot.py -r _MET_50to100
python merge_plot.py -r _MET_100toInf
python merge_plot.py -r _Nvtx_0to25
python merge_plot.py -r _Nvtx_25toInf
