import sys
try:
    sys.path.append("C:/root_v5.34.30/bin")
except:
    pass
import ROOT
import time
from math import *
from array import array
import os

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
global_branch_dic = {}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
def check_trig_exist(branch_name):
	if not (branch_name in global_branch_dic):
		global_branch_dic[branch_name] = False
		print "check trig error: %s"%(branch_name)
	return global_branch_dic[branch_name]

def match_trigger_part(trig_eta, trig_phi, obj_eta, obj_phi, dr_in):
	tmp_trig_p4 = ROOT.TLorentzVector()
	tmp_trig_p4.SetPtEtaPhiM(10.0, trig_eta, trig_phi, 1.0)
	tmp_obj_p4 = ROOT.TLorentzVector()
	tmp_obj_p4.SetPtEtaPhiM(10.0, obj_eta, obj_phi, 1.0)
	if tmp_trig_p4.DeltaR(tmp_obj_p4) <= dr_in:
		return True
	return False

def match_trigger(event, trig_eta_str, trig_phi_str, obj_eta_str, obj_phi_str, dr_in):
	if check_trig_exist(trig_eta_str) and check_trig_exist(trig_phi_str):
		trig_eta_vector = getattr(event, trig_eta_str)
		trig_phi_vector = getattr(event, trig_phi_str)
		obj_eta = getattr(event, obj_eta_str)
		obj_phi = getattr(event, obj_phi_str)
		for i in range(len(trig_eta_vector)):
			if match_trigger_part(trig_eta_vector[i], trig_phi_vector[i], obj_eta, obj_phi, dr_in):
				return True
	return False

def map_fill_hist(event, sample_hist_dic, hist_dic, path):
	pass_cut = False
	isTag = False
	isProbe = False
	isProbe_fire = False
	fill_value = -999

	if path == "name":
		pass_cut = False
		if not pass_cut:return
		isTag = False
		isProbe = False
		isProbe_fire = False
		fill_value = -999
	else:
		exec 'pass_cut = %s'%(hist_dic[path]["cut_str"])
		if not pass_cut:return
		exec 'isTag = %s'%(hist_dic[path]["isTag"])
		exec 'isProbe = %s'%(hist_dic[path]["isProbe"])
		exec 'isProbe_fire = %s'%(hist_dic[path]["isProbe_fire"])
		exec 'fill_value = %s'%(hist_dic[path]["fill_value"])
	if pass_cut and isTag and isProbe:
		sample_hist_dic[path]["h_denominator"].Fill(fill_value)
		if isProbe_fire:
			sample_hist_dic[path]["h_numerator"].Fill(fill_value)
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x_array_1 = array('f')
n_index = 0
x_array_1.append(50)
n_index += 1
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
hist_list = ["h_numerator", "h_denominator"]
hist_dic={
#DoubleEle33 trigger eff
"DouEle33Et_11":{
	"cut_str":"(0.0 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 0.79)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEG33EtUnseededFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEG33EtUnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"DouEle33Et_11",
	"use_array":False,
	"hist_para":[80,x_array_1,30,50],
	"hist":{},
	},
"DouEle33Et_12":{
	"cut_str":"(0.79 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.1)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEG33EtUnseededFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEG33EtUnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"DouEle33Et_12",
	"use_array":False,
	"hist_para":[80,x_array_1,30,50],
	"hist":{},
	},
"DouEle33Et_13":{
	"cut_str":"(1.1 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.4442)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEG33EtUnseededFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEG33EtUnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"DouEle33Et_13",
	"use_array":False,
	"hist_para":[80,x_array_1,30,50],
	"hist":{},
	},
"DouEle33Et_21":{
	"cut_str":"(1.566 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.70)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEG33EtUnseededFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEG33EtUnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"DouEle33Et_21",
	"use_array":False,
	"hist_para":[80,x_array_1,30,50],
	"hist":{},
	},
"DouEle33Et_22":{
	"cut_str":"(1.70 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.1)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEG33EtUnseededFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEG33EtUnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"DouEle33Et_22",
	"use_array":False,
	"hist_para":[80,x_array_1,30,50],
	"hist":{},
	},
"DouEle33Et_23":{
	"cut_str":"(2.1 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.5)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEG33EtUnseededFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEG33EtUnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"DouEle33Et_23",
	"use_array":False,
	"hist_para":[80,x_array_1,30,50],
	"hist":{},
	},
"DouEle33ID_1":{
	"cut_str":"(0.0 < abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.4442)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEG33EtUnseededFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEG33EtUnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEle33CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEle33CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"DouEle33ID_1",
	"use_array":False,
	"hist_para":[31,x_array_1,35,140],
	"hist":{},
	},
"DouEle33ID_2":{
	"cut_str":"(1.566 < abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.5)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEG33EtUnseededFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEG33EtUnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEle33CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEle33CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"DouEle33ID_2",
	"use_array":False,
	"hist_para":[31,x_array_1,35,140],
	"hist":{},
	},
"DouEle33_11":{
	"cut_str":"(0.0 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 0.79)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEle33CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEle33CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"DouEle33_11",
	"use_array":False,
	"hist_para":[80,x_array_1,30,50],
	"hist":{},
	},
"DouEle33_12":{
	"cut_str":"(0.79 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.1)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEle33CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEle33CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"DouEle33_12",
	"use_array":False,
	"hist_para":[80,x_array_1,30,50],
	"hist":{},
	},
"DouEle33_13":{
	"cut_str":"(1.1 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.4442)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEle33CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEle33CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"DouEle33_13",
	"use_array":False,
	"hist_para":[80,x_array_1,30,50],
	"hist":{},
	},
"DouEle33_21":{
	"cut_str":"(1.566 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.70)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEle33CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEle33CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"DouEle33_21",
	"use_array":False,
	"hist_para":[80,x_array_1,30,50],
	"hist":{},
	},
"DouEle33_22":{
	"cut_str":"(1.70 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.1)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEle33CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEle33CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"DouEle33_22",
	"use_array":False,
	"hist_para":[80,x_array_1,30,50],
	"hist":{},
	},
"DouEle33_23":{
	"cut_str":"(2.1 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.5)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEle33CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEle33CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"DouEle33_23",
	"use_array":False,
	"hist_para":[80,x_array_1,30,50],
	"hist":{},
	},
#DoubleEle33 vs pvn
"DouEle33_pvn_11":{
	"cut_str":"(0.0 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 0.79)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEle33CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEle33CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_n')",
	"hist_name":"DouEle33_pvn_11",
	"use_array":False,
	"hist_para":[100,x_array_1,0,100],
	"hist":{},
	},
"DouEle33_pvn_12":{
	"cut_str":"(0.79 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.1)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEle33CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEle33CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_n')",
	"hist_name":"DouEle33_pvn_12",
	"use_array":False,
	"hist_para":[100,x_array_1,0,100],
	"hist":{},
	},
"DouEle33_pvn_13":{
	"cut_str":"(1.1 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.4442)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEle33CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEle33CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_n')",
	"hist_name":"DouEle33_pvn_13",
	"use_array":False,
	"hist_para":[100,x_array_1,0,100],
	"hist":{},
	},
"DouEle33_pvn_21":{
	"cut_str":"(1.566 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.7)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEle33CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEle33CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_n')",
	"hist_name":"DouEle33_pvn_21",
	"use_array":False,
	"hist_para":[100,x_array_1,0,100],
	"hist":{},
	},
"DouEle33_pvn_22":{
	"cut_str":"(1.7 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.1)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEle33CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEle33CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_n')",
	"hist_name":"DouEle33_pvn_22",
	"use_array":False,
	"hist_para":[100,x_array_1,0,100],
	"hist":{},
	},
"DouEle33_pvn_23":{
	"cut_str":"(0.0 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 0.79)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEle33CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle33_CaloIdL_MW_hltDiEle33CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_n')",
	"hist_name":"DouEle33_pvn_23",
	"use_array":False,
	"hist_para":[100,x_array_1,0,100],
	"hist":{},
	},
#DoubleEle25 trigger eff
"DouEle25Et_11":{
	"cut_str":"(0.0 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 0.79)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEG25EtUnseededFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEG25EtUnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"DouEle25Et_11",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"DouEle25Et_12":{
	"cut_str":"(0.79 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.1)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEG25EtUnseededFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEG25EtUnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"DouEle25Et_12",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"DouEle25Et_13":{
	"cut_str":"(1.1 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.4442)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEG25EtUnseededFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEG25EtUnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"DouEle25Et_13",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"DouEle25Et_21":{
	"cut_str":"(1.566 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.70)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEG25EtUnseededFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEG25EtUnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"DouEle25Et_21",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"DouEle25Et_22":{
	"cut_str":"(1.70 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.1)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEG25EtUnseededFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEG25EtUnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"DouEle25Et_22",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"DouEle25Et_23":{
	"cut_str":"(2.1 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.5)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEG25EtUnseededFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEG25EtUnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"DouEle25Et_23",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"DouEle25ID_1":{
	"cut_str":"(0.0 < abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.4442)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEG25EtUnseededFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEG25EtUnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"DouEle25ID_1",
	"use_array":False,
	"hist_para":[31,x_array_1,25,130],
	"hist":{},
	},
"DouEle25ID_2":{
	"cut_str":"(1.566 < abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.5)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEG25EtUnseededFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEG25EtUnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"DouEle25ID_2",
	"use_array":False,
	"hist_para":[31,x_array_1,25,130],
	"hist":{},
	},
"DouEle25_11":{
	"cut_str":"(0.0 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 0.79)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"DouEle25_11",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"DouEle25_12":{
	"cut_str":"(0.79 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.1)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"DouEle25_12",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"DouEle25_13":{
	"cut_str":"(1.1 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.4442)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"DouEle25_13",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"DouEle25_21":{
	"cut_str":"(1.566 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.70)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"DouEle25_21",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"DouEle25_22":{
	"cut_str":"(1.70 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.1)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"DouEle25_22",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"DouEle25_23":{
	"cut_str":"(2.1 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.5)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"DouEle25_23",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
#DouEle25 vs pv_n
"DouEle25_pvn_11":{
	"cut_str":"(0.0 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 0.79)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_n')",
	"hist_name":"DouEle25_pvn_11",
	"use_array":False,
	"hist_para":[100,x_array_1,0,100],
	"hist":{},
	},
"DouEle25_pvn_12":{
	"cut_str":"(0.79 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.1)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_n')",
	"hist_name":"DouEle25_pvn_12",
	"use_array":False,
	"hist_para":[100,x_array_1,0,100],
	"hist":{},
	},
"DouEle25_pvn_13":{
	"cut_str":"(1.1 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.4442)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_n')",
	"hist_name":"DouEle25_pvn_13",
	"use_array":False,
	"hist_para":[100,x_array_1,0,100],
	"hist":{},
	},
"DouEle25_pvn_21":{
	"cut_str":"(1.566 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.7)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_n')",
	"hist_name":"DouEle25_pvn_21",
	"use_array":False,
	"hist_para":[100,x_array_1,0,100],
	"hist":{},
	},
"DouEle25_pvn_22":{
	"cut_str":"(1.7 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.1)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_n')",
	"hist_name":"DouEle25_pvn_22",
	"use_array":False,
	"hist_para":[100,x_array_1,0,100],
	"hist":{},
	},
"DouEle25_pvn_23":{
	"cut_str":"(2.1 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.5)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_n')",
	"hist_name":"DouEle25_pvn_23",
	"use_array":False,
	"hist_para":[100,x_array_1,0,100],
	"hist":{},
	},
#DouEle25 given DiEle27CaloOnly vs pv_z
"DouEle25_pvz_11":{
	"cut_str":"(0.0 < abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 0.79)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DiEle27_WPTightCaloOnly_L1DoubleEG_hltDiEle27L1DoubleEGWPTightHcalIsoFilter_eta','trig_HLT_DiEle27_WPTightCaloOnly_L1DoubleEG_hltDiEle27L1DoubleEGWPTightHcalIsoFilter_phi','probe_eta','probe_phi',0.1)",
	"isProbe":"match_trigger(event,'trig_HLT_DiEle27_WPTightCaloOnly_L1DoubleEG_hltDiEle27L1DoubleEGWPTightHcalIsoFilter_eta','trig_HLT_DiEle27_WPTightCaloOnly_L1DoubleEG_hltDiEle27L1DoubleEGWPTightHcalIsoFilter_phi','probe_eta','probe_phi',0.1)",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_z')",
	"hist_name":"DouEle25_vs_pvz_11",
	"use_array":False,
	"hist_para":[100,x_array_1,0,10],
	"hist":{},
	},
"DouEle25_pvz_12":{
	"cut_str":"(0.79 < abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.1)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DiEle27_WPTightCaloOnly_L1DoubleEG_hltDiEle27L1DoubleEGWPTightHcalIsoFilter_eta','trig_HLT_DiEle27_WPTightCaloOnly_L1DoubleEG_hltDiEle27L1DoubleEGWPTightHcalIsoFilter_phi','probe_eta','probe_phi',0.1)",
	"isProbe":"match_trigger(event,'trig_HLT_DiEle27_WPTightCaloOnly_L1DoubleEG_hltDiEle27L1DoubleEGWPTightHcalIsoFilter_eta','trig_HLT_DiEle27_WPTightCaloOnly_L1DoubleEG_hltDiEle27L1DoubleEGWPTightHcalIsoFilter_phi','probe_eta','probe_phi',0.1)",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_z')",
	"hist_name":"DouEle25_vs_pvz_12",
	"use_array":False,
	"hist_para":[100,x_array_1,0,10],
	"hist":{},
	},
"DouEle25_pvz_13":{
	"cut_str":"(1.1 < abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.4442)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DiEle27_WPTightCaloOnly_L1DoubleEG_hltDiEle27L1DoubleEGWPTightHcalIsoFilter_eta','trig_HLT_DiEle27_WPTightCaloOnly_L1DoubleEG_hltDiEle27L1DoubleEGWPTightHcalIsoFilter_phi','probe_eta','probe_phi',0.1)",
	"isProbe":"match_trigger(event,'trig_HLT_DiEle27_WPTightCaloOnly_L1DoubleEG_hltDiEle27L1DoubleEGWPTightHcalIsoFilter_eta','trig_HLT_DiEle27_WPTightCaloOnly_L1DoubleEG_hltDiEle27L1DoubleEGWPTightHcalIsoFilter_phi','probe_eta','probe_phi',0.1)",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_z')",
	"hist_name":"DouEle25_vs_pvz_13",
	"use_array":False,
	"hist_para":[100,x_array_1,0,10],
	"hist":{},
	},
"DouEle25_pvz_21":{
	"cut_str":"(1.566 < abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.7)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DiEle27_WPTightCaloOnly_L1DoubleEG_hltDiEle27L1DoubleEGWPTightHcalIsoFilter_eta','trig_HLT_DiEle27_WPTightCaloOnly_L1DoubleEG_hltDiEle27L1DoubleEGWPTightHcalIsoFilter_phi','probe_eta','probe_phi',0.1)",
	"isProbe":"match_trigger(event,'trig_HLT_DiEle27_WPTightCaloOnly_L1DoubleEG_hltDiEle27L1DoubleEGWPTightHcalIsoFilter_eta','trig_HLT_DiEle27_WPTightCaloOnly_L1DoubleEG_hltDiEle27L1DoubleEGWPTightHcalIsoFilter_phi','probe_eta','probe_phi',0.1)",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_z')",
	"hist_name":"DouEle25_vs_pvz_21",
	"use_array":False,
	"hist_para":[100,x_array_1,0,10],
	"hist":{},
	},
"DouEle25_pvz_22":{
	"cut_str":"(1.7 < abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.1)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DiEle27_WPTightCaloOnly_L1DoubleEG_hltDiEle27L1DoubleEGWPTightHcalIsoFilter_eta','trig_HLT_DiEle27_WPTightCaloOnly_L1DoubleEG_hltDiEle27L1DoubleEGWPTightHcalIsoFilter_phi','probe_eta','probe_phi',0.1)",
	"isProbe":"match_trigger(event,'trig_HLT_DiEle27_WPTightCaloOnly_L1DoubleEG_hltDiEle27L1DoubleEGWPTightHcalIsoFilter_eta','trig_HLT_DiEle27_WPTightCaloOnly_L1DoubleEG_hltDiEle27L1DoubleEGWPTightHcalIsoFilter_phi','probe_eta','probe_phi',0.1)",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_z')",
	"hist_name":"DouEle25_vs_pvz_22",
	"use_array":False,
	"hist_para":[100,x_array_1,0,10],
	"hist":{},
	},
"DouEle25_pvz_23":{
	"cut_str":"(2.1 < abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.5)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEGL1SingleAndDoubleEGNonIsoOrWithEG26WithJetAndTauFilter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltEle25CaloIdLMWPMS2Filter_phi','t_eta','t_phi',0.1) and match_trigger(event,'trig_HLT_DiEle27_WPTightCaloOnly_L1DoubleEG_hltDiEle27L1DoubleEGWPTightHcalIsoFilter_eta','trig_HLT_DiEle27_WPTightCaloOnly_L1DoubleEG_hltDiEle27L1DoubleEGWPTightHcalIsoFilter_phi','probe_eta','probe_phi',0.1)",
	"isProbe":"match_trigger(event,'trig_HLT_DiEle27_WPTightCaloOnly_L1DoubleEG_hltDiEle27L1DoubleEGWPTightHcalIsoFilter_eta','trig_HLT_DiEle27_WPTightCaloOnly_L1DoubleEG_hltDiEle27L1DoubleEGWPTightHcalIsoFilter_phi','probe_eta','probe_phi',0.1)",
	"isProbe_fire":"match_trigger(event,'trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_eta','trig_HLT_DoubleEle25_CaloIdL_MW_hltDiEle25CaloIdLMWPMS2UnseededFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_z')",
	"hist_name":"DouEle25_vs_pvz_23",
	"use_array":False,
	"hist_para":[100,x_array_1,0,10],
	"hist":{},
	},
#HLT_Ele32_WPTight
"Ele32Et_1":{
	"cut_str":"(0.0 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.4442)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele32_WPTight_Gsf_hltEG32L1SingleEGOrEtFilter_eta','trig_HLT_Ele32_WPTight_Gsf_hltEG32L1SingleEGOrEtFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele32Et_1",
	"use_array":False,
	"hist_para":[50,x_array_1,25,125],
	"hist":{},
	},
"Ele32Et_2":{
	"cut_str":"(1.566 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.5)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele32_WPTight_Gsf_hltEG32L1SingleEGOrEtFilter_eta','trig_HLT_Ele32_WPTight_Gsf_hltEG32L1SingleEGOrEtFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele32Et_2",
	"use_array":False,
	"hist_para":[50,x_array_1,25,125],
	"hist":{},
	},
"Ele32ID_1":{
	"cut_str":"(0.0 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.4442)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1)",
	"isProbe":"match_trigger(event,'trig_HLT_Ele32_WPTight_Gsf_hltEG32L1SingleEGOrEtFilter_eta','trig_HLT_Ele32_WPTight_Gsf_hltEG32L1SingleEGOrEtFilter_phi','probe_eta','probe_phi',0.1)",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele32_WPTight_Gsf_hltEle32WPTightGsfTrackIsoFilter_eta','trig_HLT_Ele32_WPTight_Gsf_hltEle32WPTightGsfTrackIsoFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele32ID_1",
	"use_array":False,
	"hist_para":[20,x_array_1,25,125],
	"hist":{},
	},
"Ele32ID_2":{
	"cut_str":"(1.566 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.5)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1)",
	"isProbe":"match_trigger(event,'trig_HLT_Ele32_WPTight_Gsf_hltEG32L1SingleEGOrEtFilter_eta','trig_HLT_Ele32_WPTight_Gsf_hltEG32L1SingleEGOrEtFilter_phi','probe_eta','probe_phi',0.1)",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele32_WPTight_Gsf_hltEle32WPTightGsfTrackIsoFilter_eta','trig_HLT_Ele32_WPTight_Gsf_hltEle32WPTightGsfTrackIsoFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele32ID_2",
	"use_array":False,
	"hist_para":[20,x_array_1,25,125],
	"hist":{},
	},
"Ele32_1":{
	"cut_str":"(0.0 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.4442)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele32_WPTight_Gsf_hltEle32WPTightGsfTrackIsoFilter_eta','trig_HLT_Ele32_WPTight_Gsf_hltEle32WPTightGsfTrackIsoFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele32_1",
	"use_array":False,
	"hist_para":[50,x_array_1,25,125],
	"hist":{},
	},
"Ele32_2":{
	"cut_str":"(1.566 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.5)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele32_WPTight_Gsf_hltEle32WPTightGsfTrackIsoFilter_eta','trig_HLT_Ele32_WPTight_Gsf_hltEle32WPTightGsfTrackIsoFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele32_2",
	"use_array":False,
	"hist_para":[50,x_array_1,25,125],
	"hist":{},
	},
"Ele32_pvn_1":{
	"cut_str":"(0.0 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.4442)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele32_WPTight_Gsf_hltEle32WPTightGsfTrackIsoFilter_eta','trig_HLT_Ele32_WPTight_Gsf_hltEle32WPTightGsfTrackIsoFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_n')",
	"hist_name":"Ele32_pvn_1",
	"use_array":False,
	"hist_para":[100,x_array_1,0,100],
	"hist":{},
	},
"Ele32_pvn_2":{
	"cut_str":"(1.566 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.5)",
	"isTag":"match_trigger(event,'trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_eta','trig_HLT_Ele35_WPTight_Gsf_hltEle35noerWPTightGsfTrackIsoFilter_phi','t_eta','t_phi',0.1)",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele32_WPTight_Gsf_hltEle32WPTightGsfTrackIsoFilter_eta','trig_HLT_Ele32_WPTight_Gsf_hltEle32WPTightGsfTrackIsoFilter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_n')",
	"hist_name":"Ele32_pvn_2",
	"use_array":False,
	"hist_para":[100,x_array_1,0,100],
	"hist":{},
	},
#Ele23_Ele12
"Ele23_Ele12_EtLeg1_11":{
	"cut_str":"(0.0 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 0.79)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg1Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg1Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele23_Ele12_EtLeg1_11",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"Ele23_Ele12_EtLeg1_12":{
	"cut_str":"(0.79 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.1)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg1Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg1Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele23_Ele12_EtLeg1_12",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"Ele23_Ele12_EtLeg1_13":{
	"cut_str":"(1.1 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.4442)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg1Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg1Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele23_Ele12_EtLeg1_13",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"Ele23_Ele12_EtLeg1_21":{
	"cut_str":"(1.566 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.7)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg1Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg1Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele23_Ele12_EtLeg1_21",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"Ele23_Ele12_EtLeg1_22":{
	"cut_str":"(1.7 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.1)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg1Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg1Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele23_Ele12_EtLeg1_22",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"Ele23_Ele12_EtLeg1_23":{
	"cut_str":"(2.1 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.5)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg1Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg1Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele23_Ele12_EtLeg1_23",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"Ele23_Ele12_IDLeg1_1":{
	"cut_str":"(0.0 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.442)",
	"isTag":"True",
	"isProbe":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg1Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg1Filter_phi','probe_eta','probe_phi',0.1)",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg1Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg1Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele23_Ele12_IDLeg1_1",
	"use_array":False,
	"hist_para":[16,x_array_1,20,100],
	"hist":{},
	},
"Ele23_Ele12_IDLeg1_2":{
	"cut_str":"(1.566 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.5)",
	"isTag":"True",
	"isProbe":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg1Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg1Filter_phi','probe_eta','probe_phi',0.1)",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg1Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg1Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele23_Ele12_IDLeg1_2",
	"use_array":False,
	"hist_para":[16,x_array_1,20,100],
	"hist":{},
	},
"Ele23_Ele12_Leg1_11":{
	"cut_str":"(0.0 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 0.79)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg1Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg1Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele23_Ele12_Leg1_11",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"Ele23_Ele12_Leg1_12":{
	"cut_str":"(0.79 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.1)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg1Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg1Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele23_Ele12_Leg1_12",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"Ele23_Ele12_Leg1_13":{
	"cut_str":"(1.1 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.4442)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg1Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg1Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele23_Ele12_Leg1_13",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"Ele23_Ele12_Leg1_21":{
	"cut_str":"(1.566 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.7)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg1Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg1Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele23_Ele12_Leg1_21",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"Ele23_Ele12_Leg1_22":{
	"cut_str":"(1.7 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.1)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg1Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg1Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele23_Ele12_Leg1_22",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"Ele23_Ele12_Leg1_23":{
	"cut_str":"(2.1 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.5)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg1Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg1Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele23_Ele12_Leg1_23",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"Ele23_Ele12_EtLeg2_11":{
	"cut_str":"(0.0 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 0.79)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg2Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg2Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele23_Ele12_EtLeg2_11",
	"use_array":False,
	"hist_para":[80,x_array_1,8,28],
	"hist":{},
	},
"Ele23_Ele12_EtLeg2_12":{
	"cut_str":"(0.79 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.1)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg2Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg2Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele23_Ele12_EtLeg2_12",
	"use_array":False,
	"hist_para":[80,x_array_1,8,28],
	"hist":{},
	},
"Ele23_Ele12_EtLeg2_13":{
	"cut_str":"(1.1 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.4442)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg2Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg2Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele23_Ele12_EtLeg2_13",
	"use_array":False,
	"hist_para":[80,x_array_1,8,28],
	"hist":{},
	},
"Ele23_Ele12_EtLeg2_21":{
	"cut_str":"(1.566 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.7)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg2Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg2Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele23_Ele12_EtLeg2_21",
	"use_array":False,
	"hist_para":[80,x_array_1,8,28],
	"hist":{},
	},
"Ele23_Ele12_EtLeg2_22":{
	"cut_str":"(1.7 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.1)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg2Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg2Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele23_Ele12_EtLeg2_22",
	"use_array":False,
	"hist_para":[80,x_array_1,8,28],
	"hist":{},
	},
"Ele23_Ele12_EtLeg2_23":{
	"cut_str":"(2.1 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.5)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg2Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg2Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele23_Ele12_EtLeg2_23",
	"use_array":False,
	"hist_para":[80,x_array_1,8,28],
	"hist":{},
	},
"Ele23_Ele12_IDLeg2_1":{
	"cut_str":"(0.0 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.442)",
	"isTag":"True",
	"isProbe":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg2Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg2Filter_phi','probe_eta','probe_phi',0.1)",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg2Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg2Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele23_Ele12_IDLeg2_1",
	"use_array":False,
	"hist_para":[18,x_array_1,10,100],
	"hist":{},
	},
"Ele23_Ele12_IDLeg2_2":{
	"cut_str":"(1.566 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.5)",
	"isTag":"True",
	"isProbe":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg2Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLEtLeg2Filter_phi','probe_eta','probe_phi',0.1)",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg2Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg2Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele23_Ele12_IDLeg2_2",
	"use_array":False,
	"hist_para":[18,x_array_1,10,100],
	"hist":{},
	},
"Ele23_Ele12_Leg2_11":{
	"cut_str":"(0.0 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 0.79)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg2Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg2Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele23_Ele12_Leg2_11",
	"use_array":False,
	"hist_para":[80,x_array_1,8,28],
	"hist":{},
	},
"Ele23_Ele12_Leg2_12":{
	"cut_str":"(0.79 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.1)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg2Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg2Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele23_Ele12_Leg2_12",
	"use_array":False,
	"hist_para":[80,x_array_1,8,28],
	"hist":{},
	},
"Ele23_Ele12_Leg2_13":{
	"cut_str":"(1.1 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.4442)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg2Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg2Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele23_Ele12_Leg2_13",
	"use_array":False,
	"hist_para":[80,x_array_1,8,28],
	"hist":{},
	},
"Ele23_Ele12_Leg2_21":{
	"cut_str":"(1.566 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.7)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg2Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg2Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele23_Ele12_Leg2_21",
	"use_array":False,
	"hist_para":[80,x_array_1,8,28],
	"hist":{},
	},
"Ele23_Ele12_Leg2_22":{
	"cut_str":"(1.7 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.1)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg2Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg2Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele23_Ele12_Leg2_22",
	"use_array":False,
	"hist_para":[80,x_array_1,8,28],
	"hist":{},
	},
"Ele23_Ele12_Leg2_23":{
	"cut_str":"(2.1 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.5)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg2Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg2Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'probe_pt')",
	"hist_name":"Ele23_Ele12_Leg2_23",
	"use_array":False,
	"hist_para":[80,x_array_1,8,28],
	"hist":{},
	},
#Ele23_Ele12 vs pvn
"Ele23_Ele12_Leg1_pvn_11":{
	"cut_str":"(0.0 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 0.79)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg1Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg1Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_n')",
	"hist_name":"Ele23_Ele12_Leg1_pvn_11",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"Ele23_Ele12_Leg1_pvn_12":{
	"cut_str":"(0.79 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.1)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg1Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg1Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_n')",
	"hist_name":"Ele23_Ele12_Leg1_pvn_12",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"Ele23_Ele12_Leg1_pvn_13":{
	"cut_str":"(1.1 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.4442)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg1Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg1Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_n')",
	"hist_name":"Ele23_Ele12_Leg1_pvn_13",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"Ele23_Ele12_Leg1_pvn_21":{
	"cut_str":"(1.566 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.7)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg1Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg1Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_n')",
	"hist_name":"Ele23_Ele12_Leg1_pvn_21",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"Ele23_Ele12_Leg1_pvn_22":{
	"cut_str":"(1.7 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.1)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg1Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg1Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_n')",
	"hist_name":"Ele23_Ele12_Leg1_pvn_22",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"Ele23_Ele12_Leg1_pvn_23":{
	"cut_str":"(2.1 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.5)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg1Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg1Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_n')",
	"hist_name":"Ele23_Ele12_Leg1_pvn_23",
	"use_array":False,
	"hist_para":[80,x_array_1,20,40],
	"hist":{},
	},
"Ele23_Ele12_Leg2_pvn_11":{
	"cut_str":"(0.0 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 0.79)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg2Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg2Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_n')",
	"hist_name":"Ele23_Ele12_Leg2_pvn_11",
	"use_array":False,
	"hist_para":[100,x_array_1,0,100],
	"hist":{},
	},
"Ele23_Ele12_Leg2_pvn_12":{
	"cut_str":"(0.79 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.1)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg2Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg2Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_n')",
	"hist_name":"Ele23_Ele12_Leg2_pvn_12",
	"use_array":False,
	"hist_para":[100,x_array_1,0,100],
	"hist":{},
	},
"Ele23_Ele12_Leg2_pvn_13":{
	"cut_str":"(1.1 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.4442)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg2Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg2Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_n')",
	"hist_name":"Ele23_Ele12_Leg2_pvn_13",
	"use_array":False,
	"hist_para":[100,x_array_1,0,100],
	"hist":{},
	},
"Ele23_Ele12_Leg2_pvn_21":{
	"cut_str":"(1.566 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 1.7)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg2Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg2Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_n')",
	"hist_name":"Ele23_Ele12_Leg2_pvn_21",
	"use_array":False,
	"hist_para":[100,x_array_1,0,100],
	"hist":{},
	},
"Ele23_Ele12_Leg2_pvn_22":{
	"cut_str":"(1.7 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.1)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg2Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg2Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_n')",
	"hist_name":"Ele23_Ele12_Leg2_pvn_22",
	"use_array":False,
	"hist_para":[100,x_array_1,0,100],
	"hist":{},
	},
"Ele23_Ele12_Leg2_pvn_23":{
	"cut_str":"(2.1 <= abs(getattr(event,'probe_sc_eta')) and abs(getattr(event,'probe_sc_eta')) < 2.5)",
	"isTag":"True",
	"isProbe":"True",
	"isProbe_fire":"match_trigger(event,'trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg2Filter_eta','trig_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_hltEle23Ele12CaloIdLTrackIdLIsoVLTrackIsoLeg2Filter_phi','probe_eta','probe_phi',0.1)",
	"fill_value":"getattr(event,'pv_n')",
	"hist_name":"Ele23_Ele12_Leg2_pvn_23",
	"use_array":False,
	"hist_para":[100,x_array_1,0,100],
	"hist":{},
	},
}
