sys_dic = {
#"sys name":["sys label","need run data",have hist,commmon sys weight],
"norminal":["norminal",True,True,0],
"muptscalu":["muptscalu",True,True,0],
"muptresu":["muptresu",True,True,0],
"eletscalu":["eletscalu",True,True,0],
"eletscald":["eletscald",True,True,0],
"top1_u":["top1_u",True,True,0],
"top1_d":["top1_d",True,True,0],
"pu_u":["pu_u",True,True,0],
"pu_d":["pu_d",True,True,0],

"qcd_u":["qcd_u",False,True,0],
"qcd_d":["qcd_d",False,True,0],
"xs_ttbar_u":["xs_ttbar_u",False,True,0],
"xs_ttbar_d":["xs_ttbar_d",False,True,0],
"xs_ww_u":["xs_ww_u",False,True,0],
"xs_ww_d":["xs_ww_d",False,True,0],
"xs_st_u":["xs_st_u",False,True,0],
"xs_st_d":["xs_st_d",False,True,0],
"xs_dy_u":["xs_dy_u",False,True,0],
"xs_dy_d":["xs_dy_d",False,True,0],
"xs_wz_u":["xs_wz_u",False,True,0],
"xs_wz_d":["xs_wz_d",False,True,0],
"xs_zz_u":["xs_zz_u",False,True,0],
"xs_zz_d":["xs_zz_d",False,True,0],

#"murecoid":["",False,False,0],
"mu_sf":["mu_sf",False,False,0.016],
"el_sf":["el_sf",False,False,0.002],
"lumi":["lumi",False,False,0.024],
#"":["",False,False,0],
}
