cp -r default ddpi-2
cp -r default ddpi-3
cp -r default ddpi-4
cp -r default pipijpsi-2
cp -r default pipijpsi-3
cp -r default pipijpsi-4
cp -r default pipihc-2
cp -r default pipihc-3
cp -r default pipihc-4
