python extract_plot.py -r _ALL
python extract_plot.py -r _ALL_lepveto
python extract_plot.py -r _FKE_ALL
python extract_plot.py -r _FKE_ALL_lepveto
python extract_plot.py -r _FKE_highEleEt
python extract_plot.py -r _FKE_highEleEt_lepveto
python extract_plot.py -r _FKM_ALL
python extract_plot.py -r _FKM_ALL_lepveto
python extract_plot.py -r _FKM_highEleEt
python extract_plot.py -r _FKM_highEleEt_lepveto
python extract_plot.py -r _FK_ALL
python extract_plot.py -r _FK_ALL_lepveto
python extract_plot.py -r _FK_highEleEt
python extract_plot.py -r _FK_highEleEt_lepveto
python extract_plot.py -r _highEleEt
python extract_plot.py -r _highEleEt_lepveto
