sys_dic = {}
#"sys name":["sys label","need run data",have hist, not use now],
sys_dic["nominal"]:["nominal",True,True,0]
sys_dic["muptscalu"]:["muptscalu",True,True,0]
sys_dic["muptresu"]:["muptresu",True,True,0]
sys_dic["eletscalu"]:["eletscalu",True,True,0]
sys_dic["eletscald"]:["eletscald",True,True,0]
sys_dic["top1_u"]:["top1_u",True,True,0]
sys_dic["top1_d"]:["top1_d",True,True,0]
sys_dic["pu_u"]:["pu_u",True,True,0]
sys_dic["pu_d"]:["pu_d",True,True,0]

sys_dic["mu_id_sfu"]:["mu_id_sfu",True,True,0]
sys_dic["mu_iso_sfu"]:["mu_iso_sfu",True,True,0]
sys_dic["mu_trig_sfu"]:["mu_trig_sfu",True,True,0]
sys_dic["el_id_sfu"]:["el_id_sfu",True,True,0]
sys_dic["mu_id_sfd"]:["mu_id_sfd",True,True,0]
sys_dic["mu_iso_sfd"]:["mu_iso_sfd",True,True,0]
sys_dic["mu_trig_sfd"]:["mu_trig_sfd",True,True,0]
sys_dic["el_id_sfd"]:["el_id_sfd",True,True,0]

sys_dic["qcd_u"]:["qcd_u",False,True,0]
sys_dic["qcd_d"]:["qcd_d",False,True,0]
sys_dic["xs_ttbar_u"]:["xs_ttbar_u",False,True,0]
sys_dic["xs_ttbar_d"]:["xs_ttbar_d",False,True,0]
sys_dic["xs_ww_u"]:["xs_ww_u",False,True,0]
sys_dic["xs_ww_d"]:["xs_ww_d",False,True,0]
sys_dic["xs_st_u"]:["xs_st_u",False,True,0]
sys_dic["xs_st_d"]:["xs_st_d",False,True,0]
sys_dic["xs_dy_u"]:["xs_dy_u",False,True,0]
sys_dic["xs_dy_d"]:["xs_dy_d",False,True,0]
sys_dic["xs_wz_u"]:["xs_wz_u",False,True,0]
sys_dic["xs_wz_d"]:["xs_wz_d",False,True,0]
sys_dic["xs_zz_u"]:["xs_zz_u",False,True,0]
sys_dic["xs_zz_d"]:["xs_zz_d",False,True,0]
sys_dic["lumi_u"]:["lumi_u",False,True,0]
sys_dic["lumi_d"]:["lumi_d",False,True,0]