mkdir output
hadd -f output/80_madgraph_DYToLL_10to50.root        batchmc/*80_madgraph_DYToLL_10to50*.root		
hadd -f output/80_madgraph_DYToLL_50.root            batchmc/*80_madgraph_DYToLL_50*.root		
hadd -f output/80_DYToLL_10to50.root        batchmc/*80_DYToLL_10to50*.root		
hadd -f output/80_DYToLL_50.root            batchmc/*80_DYToLL_50*.root		
hadd -f output/80_TTGJets.root              batchmc/*80_TTGJets*.root			
hadd -f output/80_TTTo2L2Nu.root            batchmc/*80_TTTo2L2Nu*.root		
hadd -f output/80_TTWJetsToLNu.root         batchmc/*80_TTWJetsToLNu*.root		
hadd -f output/80_TTWJetsToQQ.root          batchmc/*80_TTWJetsToQQ*.root		
hadd -f output/80_TTZToLLNuNu_10.root       batchmc/*80_TTZToLLNuNu_10*.root		
hadd -f output/80_TTZToQQ.root              batchmc/*80_TTZToQQ*.root			
hadd -f output/80_WGToLNuG.root             batchmc/*80_WGToLNuG*.root			
hadd -f output/80_WJetsToLNu.root           batchmc/*80_WJetsToLNu*.root		
hadd -f output/80_WWTo2L2Nu.root            batchmc/*80_WWTo2L2Nu*.root		
hadd -f output/80_WZTo2L2Q.root             batchmc/*80_WZTo2L2Q*.root			
hadd -f output/80_WZTo3LNu.root             batchmc/*80_WZTo3LNu*.root			
hadd -f output/80_ZZTo2L2Nu.root            batchmc/*80_ZZTo2L2Nu*.root		
hadd -f output/80_ZZTo4L.root               batchmc/*80_ZZTo4L*.root			
hadd -f output/80_tW.root                   batchmc/*80_tW_0*.root			
hadd -f output/80_tW_anti.root              batchmc/*80_tW_anti*.root			
hadd -f output/80_tW_ll.root                batchmc/*80_tW_*.root			
hadd -f output/80_DY_ll.root                batchmc/*80_DYToLL_*.root			
