ln -s ../MC_data/DYToLL_all.root .
ln -s ../MC_data/DYToLL_1.root .
ln -s ../MC_data/DYToLL_2.root .
ln -s ../MC_data/DYToLL_3.root .
ln -s ../MC_data/DYToLL_4.root .
ln -s ../MC_data/DYToLL_5.root .
ln -s ../MC_data/DYToLL_6.root .
ln -s ../MC_data/DYToLL_7.root .
ln -s ../MC_data/DYToLL_8.root .
ln -s ../MC_data/DYToLL_9.root .
ln -s ../MC_data/ST.root .
ln -s ../MC_data/WJets.root .
ln -s ../MC_data/WW_all.root .
ln -s ../MC_data/WW1.root .
ln -s ../MC_data/WW2.root .
ln -s ../MC_data/WW3.root .
ln -s ../MC_data/WW4.root .
ln -s ../MC_data/WW5.root .
ln -s ../MC_data/WZ.root .
ln -s ../MC_data/ZZ.root .
ln -s ../MC_data/data_2016_SingleMuon_SinglePhoton2.root .
ln -s ../MC_data/fk_DYToLL_all.root .
ln -s ../MC_data/fk_DYToLL_1.root .
ln -s ../MC_data/fk_DYToLL_2.root .
ln -s ../MC_data/fk_DYToLL_3.root .
ln -s ../MC_data/fk_DYToLL_4.root .
ln -s ../MC_data/fk_DYToLL_5.root .
ln -s ../MC_data/fk_DYToLL_6.root .
ln -s ../MC_data/fk_DYToLL_7.root .
ln -s ../MC_data/fk_DYToLL_8.root .
ln -s ../MC_data/fk_DYToLL_9.root .
ln -s ../MC_data/fk_ST.root .
ln -s ../MC_data/fk_WJets.root .
ln -s ../MC_data/fk_WW_all.root .
ln -s ../MC_data/fk_WW1.root .
ln -s ../MC_data/fk_WW2.root .
ln -s ../MC_data/fk_WW3.root .
ln -s ../MC_data/fk_WW4.root .
ln -s ../MC_data/fk_WW5.root .
ln -s ../MC_data/fk_WZ.root .
ln -s ../MC_data/fk_ZZ.root .
ln -s ../MC_data/fk_data_2016_SingleMuon_SinglePhoton2.root .
ln -s ../MC_data/fk_ttbar.root .
ln -s ../MC_data/fk_ttbar2l2u_all.root .
ln -s ../MC_data/fk_ttbar2l2u_1.root .
ln -s ../MC_data/fk_ttbar2l2u_2.root .
ln -s ../MC_data/fk_ttbar2l2u_3.root .
ln -s ../MC_data/fk_ttbar2l2u_4.root .
ln -s ../MC_data/fk_ttbar2l2u_5.root .
ln -s ../MC_data/ttbar.root .
ln -s ../MC_data/ttbar2l2u_all.root .
ln -s ../MC_data/ttbar2l2u_1.root .
ln -s ../MC_data/ttbar2l2u_2.root .
ln -s ../MC_data/ttbar2l2u_3.root .
ln -s ../MC_data/ttbar2l2u_4.root .
ln -s ../MC_data/ttbar2l2u_5.root .
