cp -r default ddpi-2
cp -r default ddpi-3
cp -r default ddpi-4
cp -r default ddpi-5
cp -r default ddpi-6
cp -r default ddpi-7
cp -r default ddpi-8
cp -r default pipijpsi-2
cp -r default pipijpsi-3
cp -r default pipijpsi-4
cp -r default pipihc-2
cp -r default pipihc-3
cp -r default pipihc-4
